### PR TITLE
Contribute CI, cabalize testsuite

### PR DESCRIPTION
**Pull request by andreasabel**
- Fix unused import warnings (import `Control.Applicative` only for GHC < 7.10)
- Modernize `.cabal` file
- Migrate testsuite to `tasty-hunit`, add to `.cabal` file
- Autogenerated full-featured Haskell-CI for GHC 7.0 - 9.6
  Successful run at: https://github.com/andreasabel/easy-file/actions/runs/4396681984
- Minimal CI (build/test) for macOS and Windows (latest GHC)
  Successful run at: https://github.com/andreasabel/easy-file/actions/runs/4396681986

### CODE REVIEW

**Comment by andreasabel** [comment]
@kazu-yamamoto : CI ran successfully, PR is ready.

**Review by kazu-yamamoto — APPROVED** [review]
Very nice!

**Comment by kazu-yamamoto** [comment]
Merged.
Thank you for your contribution!

If you wish, I will release a new version.

**Comment by andreasabel** [comment]
@kazu-yamamoto : If it is not too much effort, you could release 0.2.2.1 so that the import warnings no longer show up when compiling `easy-file`.  That would be nice.

**Comment by kazu-yamamoto** [comment]
A new version has been released.

**Pull request merged**
